apiVersion: v1
kind: ResourceQuota
metadata:
  name: grade-demo-quota
  namespace: grade-demo
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "2Gi"
    limits.cpu: "4"
    limits.memory: "4Gi"
    pods: "10"
